[project]
name = "poseeditor"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.10"
dependencies = [
    "numpy>=2.0.2",
    "openai-whisper>=20250625",
    "pyaudio>=0.2.14",
    "pyside6>=6.10.1",
    "pyinstaller>=6.0.0",
]
