[project]
name = "poseeditor"
version = "3.0.4"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.10"
dependencies = [
    "numpy>=2.0.2",
    "pyside6>=6.10.1",
    "pyinstaller>=6.0.0",
]
